// <auto-generated />
using System;
using InventoryManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817225552_AddAccessControl")]
    partial class AddAccessControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and accessories",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Food and household goods",
                            IsActive = true,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office furniture and supplies",
                            IsActive = true,
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Quantity_NonNegative", "[Quantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Quantity = 12,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Quantity = 18,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000007"),
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000008"),
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000009"),
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000010"),
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000011"),
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000012"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000012"),
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000013"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000013"),
                            Quantity = 11,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000014"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000014"),
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000015"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000015"),
                            Quantity = 22,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000016"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000016"),
                            Quantity = 47,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000017"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000017"),
                            Quantity = 28,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000018"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000018"),
                            Quantity = 22,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000019"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000019"),
                            Quantity = 47,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000020"),
                            ProductId = new Guid("30000000-0000-0000-0000-000000000020"),
                            Quantity = 32,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 50,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000001"),
                            QuantityChange = 50,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 25,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000002"),
                            QuantityChange = 25,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 12,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000003"),
                            QuantityChange = 12,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 45,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000004"),
                            QuantityChange = 45,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 18,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000005"),
                            QuantityChange = 18,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 55,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000006"),
                            QuantityChange = 55,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 30,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000007"),
                            QuantityChange = 30,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 20,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000008"),
                            QuantityChange = 20,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 50,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000009"),
                            QuantityChange = 50,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 30,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000010"),
                            QuantityChange = 30,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 50,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000011"),
                            QuantityChange = 50,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 15,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000012"),
                            QuantityChange = 15,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 11,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000013"),
                            QuantityChange = 11,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 55,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000014"),
                            QuantityChange = 55,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 22,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000015"),
                            QuantityChange = 22,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 47,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000016"),
                            QuantityChange = 47,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 28,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000017"),
                            QuantityChange = 28,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 22,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000018"),
                            QuantityChange = 22,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 47,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000019"),
                            QuantityChange = 47,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            NewQuantity = 32,
                            PreviousQuantity = 0,
                            ProductId = new Guid("30000000-0000-0000-0000-000000000020"),
                            QuantityChange = 32,
                            Reason = "Initial stock on setup",
                            Type = 1,
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Description = "Create new user accounts",
                            Name = "User.Create"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Description = "Edit user profile fields",
                            Name = "User.Edit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Description = "Deactivate (disable) user accounts",
                            Name = "User.Deactivate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Description = "Assign a role to a user (replaces their permissions with the role defaults)",
                            Name = "User.AssignRole"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Description = "Grant and revoke user permissions",
                            Name = "User.ManagePermissions"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            Description = "Create products",
                            Name = "Product.Create"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000007"),
                            Description = "Edit products",
                            Name = "Product.Edit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000008"),
                            Description = "View products",
                            Name = "Product.View"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000009"),
                            Description = "Deactivate products",
                            Name = "Product.Deactivate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000010"),
                            Description = "Activate products",
                            Name = "Product.Activate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000011"),
                            Description = "Create categories",
                            Name = "Category.Create"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000012"),
                            Description = "Edit categories",
                            Name = "Category.Edit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000013"),
                            Description = "View categories",
                            Name = "Category.View"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000014"),
                            Description = "Deactivate categories",
                            Name = "Category.Deactivate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000015"),
                            Description = "Activate categories",
                            Name = "Category.Activate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000016"),
                            Description = "Hard-delete categories",
                            Name = "Category.Delete"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000017"),
                            Description = "Create warehouses",
                            Name = "Warehouse.Create"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000018"),
                            Description = "Edit warehouses (warehouse-scoped)",
                            Name = "Warehouse.Edit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000019"),
                            Description = "View warehouses",
                            Name = "Warehouse.View"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000020"),
                            Description = "Deactivate warehouses (warehouse-scoped)",
                            Name = "Warehouse.Deactivate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000021"),
                            Description = "Activate warehouses (warehouse-scoped)",
                            Name = "Warehouse.Activate"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000022"),
                            Description = "View inventory and stock movement (transactions)",
                            Name = "Inventory.View"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000023"),
                            Description = "Adjust stock counts (warehouse-scoped)",
                            Name = "Inventory.Adjust"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000024"),
                            Description = "Create orders",
                            Name = "Order.Create"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000025"),
                            Description = "Edit orders",
                            Name = "Order.Edit"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000026"),
                            Description = "Cancel orders",
                            Name = "Order.Cancel"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000027"),
                            Description = "Complete (fulfill) orders (warehouse-scoped)",
                            Name = "Order.Complete"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000028"),
                            Description = "View all orders",
                            Name = "Order.View"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000029"),
                            Description = "View own orders only",
                            Name = "Order.ViewOwn"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000030"),
                            Description = "Add line items to orders",
                            Name = "OrderItem.Add"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000031"),
                            Description = "Remove line items from orders",
                            Name = "OrderItem.Remove"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000032"),
                            Description = "View order reports",
                            Name = "Report.ViewOrders"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000033"),
                            Description = "View inventory reports",
                            Name = "Report.ViewInventory"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000034"),
                            Description = "View transaction reports",
                            Name = "Report.ViewTransactions"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000035"),
                            Description = "View warehouse summary reports",
                            Name = "Report.ViewWarehouseSummary"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "iPhone 15",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Samsung 55 TV",
                            Price = 649.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dell XPS 13 Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Bluetooth Headphones",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Smart Watch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Basmati Rice 5kg",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Canned Beans",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Olive Oil",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fresh Bread",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Almonds",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Office Chair",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Desk Lamp",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Notebook Set",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Pen Set",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Stapler",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "T-Shirt",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jacket",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Blender",
                            Price = 59.99m
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Name = "Main Warehouse",
                            Type = "Warehouse"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Name = "Alexandria Warehouse",
                            Type = "Warehouse"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            Name = "Cairo Warehouse",
                            Type = "Warehouse"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Name = "WarehouseOperator"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Name = "SalesAgent"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "System Admin",
                            Email = "admin@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.MBzYxHzXa5ldDEWJ/l9oQg==.MP5l6mZmU1DpWNWDFJJoughwJ83sLGWVEN1DC+t9I5M=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin2",
                            Email = "admin2@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.6u4ePiGDvOinOE45tjhHsA==.f4z3B7MINBuJu9tcM17xDV9J5rwCyUtaAcv93OBJtAA=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Ahmed Hassan",
                            Email = "ahmed@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.Bs0wWo3rhMJ4dh2IGmp8BQ==.coVOKfh2h6uNEcjuP1uqkSxBlfZ1HV5/nSa03XCJhcM=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Username = "ahmed"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sara Mohamed",
                            Email = "sara@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.IUNFcOuRzyrW2TR497uubA==.6gQmot5WpeY3qPVa+71QKNJsAf8IUhWpOGn5Ri7YHiY=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Username = "sara"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mohamed Ali",
                            Email = "mohamed@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.j3jvp6L3MnN649wsRRMT6A==.X+FdMk0qGX1xq4tGgg3PcoQGeW3ddONzDvFCG0vC0o0=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Username = "mohamed"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manager",
                            Email = "manager@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.k19uFWjMCAzN+mGFdto86w==.z7SieNjkQ+HoYMlIfG815EZr7r54bCc/jF8FHWHc5Do=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Username = "manager"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sales Agent One",
                            Email = "sales1@inventory.local",
                            IsActive = true,
                            PasswordHash = "100000.dxsBi574BJhxiOFR6stu7Q==.zY8XemzTza1R4uCnyBq2v+con1+G6srKZcCsxJfEiFg=",
                            RoleId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Username = "sales1"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique()
                        .HasFilter("[ResourceId] IS NULL");

                    b.HasIndex("UserId", "PermissionId", "ResourceId")
                        .IsUnique()
                        .HasFilter("[ResourceId] IS NOT NULL");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000000"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000019"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000022"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000023"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000028"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000027"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000019"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000022"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000023"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000010"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000028"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000011"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000027"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000012"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000013"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000019"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000014"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000022"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000015"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000023"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000016"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000028"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000017"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000027"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000018"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000013"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000019"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000020"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000019"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000021"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000022"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000022"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000028"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000023"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000032"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000024"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000033"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000025"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000034"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000026"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000035"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000027"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000028"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000024"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000029"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000025"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000030"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000026"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000031"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000029"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000032"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000030"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000033"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000031"),
                            UserId = new Guid("40000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Downtown, Cairo",
                            Name = "Main Warehouse",
                            ResourceId = new Guid("70000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Alexandria",
                            Name = "Alexandria Warehouse",
                            ResourceId = new Guid("70000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Nasr City, Cairo",
                            Name = "Cairo Warehouse",
                            ResourceId = new Guid("70000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.WarehouseOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("WarehouseId", "OperatorUserId")
                        .IsUnique();

                    b.ToTable("WarehouseOperators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            OperatorUserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            OperatorUserId = new Guid("40000000-0000-0000-0000-000000000004"),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            OperatorUserId = new Guid("40000000-0000-0000-0000-000000000005"),
                            WarehouseId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Inventory", null)
                        .WithMany("Transactions")
                        .HasForeignKey("InventoryId");

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.OrderHistory", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Order", "Order")
                        .WithMany("History")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Product", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Resource", "Resource")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.WarehouseOperator", b =>
                {
                    b.HasOne("InventoryManagementSystem.Domain.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Operators")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Order", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Resource", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Operators");
                });
#pragma warning restore 612, 618
        }
    }
}
